function RUNTIME = ep_TimerFcn_Start(CONFIG, RUNTIME, AX)
% RUNTIME = ep_TimerFcn_Start(CONFIG, RUNTIME, RP)
% RUNTIME = ep_TimerFcn_Start(CONFIG, RUNTIME, DA)
% RUNTIME = ep_TimerFcn_Start(CONFIG, RUNTIME, SYN)
% 
% Default Start timer function
% 
% Initialize parameters and take care of some other things just before
% beginning experiment
% 
% Use ep_PsychConfig GUI to specify custom timer function.
% 
% Daniel.Stolzberg@gmail.com 2019

% Copyright (C) 2019  Daniel Stolzberg, PhD

E = EPsychInfo;



% make temporary directory in current folder for storing data during
% runtime in case of a computer crash or Matlab error
if ~isfield(RUNTIME,'DataDir') || ~isfolder(RUNTIME.DataDir)
    RUNTIME.DataDir = fullfile(fileparts(E.root),'DATA');
end
if ~isfolder(RUNTIME.DataDir), mkdir(RUNTIME.DataDir); end

RUNTIME.NSubjects = length(CONFIG);

RUNTIME.HELPER = epsych.Helper;

for i = 1:RUNTIME.NSubjects
    C = CONFIG(i);

    RUNTIME.TRIALS(i).trials       = C.PROTOCOL.COMPILED.trials;
    RUNTIME.TRIALS(i).TrialCount   = zeros(size(RUNTIME.TRIALS(i).trials,1),1); 
    RUNTIME.TRIALS(i).activeTrials = true(size(RUNTIME.TRIALS(i).TrialCount));
    RUNTIME.TRIALS(i).UserData     = [];
    RUNTIME.TRIALS(i).trialfunc    = C.PROTOCOL.OPTIONS.trialfunc;

    RUNTIME.TRIALS(i).moduleName = RUNTIME.TDT.Module_{1}; % TO DO: make sure we're looking at correct module if using multiple modules


    for j = 1:length(RUNTIME.TRIALS(i).readparams)
        
        if RUNTIME.usingSynapse
            ptag = RUNTIME.TRIALS(i).readparams_{j};
            dt = AX.getParameterInfo(RUNTIME.TRIALS(i).moduleName,ptag);
            dt = dt.Type(1);
        else
            ptag = RUNTIME.TRIALS(i).Mreadparams{j};
            lut = RUNTIME.TRIALS(i).RPread_lut(j);
            dt  = AX(lut).GetTagType(ptag);    
        end

        if isempty(deblank(char(dt))), dt = {'S'}; end % PA5
        RUNTIME.TRIALS(i).datatype{j} = char(dt);
    end
    
    RUNTIME.TRIALS(i).Subject = C.SUBJECT;
    RUNTIME.TRIALS(i).BoxID = C.SUBJECT.BoxID; % make BoxID more easily accessible DJS 1/14/2016



    %Add ephys field to subject structure if running Synapse
    if RUNTIME.usingSynapse
        RUNTIME.TRIALS(i).Subject.Synapse.user      = AX.getCurrentUser();
        RUNTIME.TRIALS(i).Subject.Synapse.subject   = AX.getCurrentSubject();
        RUNTIME.TRIALS(i).Subject.Synapse.experiment = AX.getCurrentExperiment();
        RUNTIME.TRIALS(i).Subject.Synapse.tank      = AX.getCurrentTank();
        RUNTIME.TRIALS(i).Subject.Synapse.block     = AX.getCurrentBlock();
    end
    



    % Initialze required parameters generated by behavior macros
    bmn = {'RespCode','TrigState','NewTrial','ResetTrig','TrialNum', ...
        'TrialComplete','AcqBuffer','AcqBufferSize'};
    for cc = bmn
        c = char(cc);
        % SYNAPSE does not allow for reading parameters with # prefix. We
        % will now use a single underscore, "_", as the prefix to denote
        % hidden macro parameters.
        RUNTIME.(sprintf('%sStr',c)){i} = sprintf('_%s~%d',c,RUNTIME.TRIALS(i).Subject.BoxID);
    end


    % Create data file for saving data during runtime in case there is a problem
    % * this file will automatically be overwritten

    % Create data file info structure
    info.Subject = RUNTIME.TRIALS(i).Subject;
    info.CompStartTimestamp = datetime("now");
    info.EPsychMeta = E.meta;
    [~, computer] = system('hostname'); 
    info.Computer = strtrim(computer);
    
    dfn = sprintf('RUNTIME_DATA_%s_Box_%02d_%s.mat', ...
        genvarname(RUNTIME.TRIALS(i).Subject.Name), ...
        RUNTIME.TRIALS(i).Subject.BoxID,datetime('today',Format='MMM-dd-yyyy'));
    RUNTIME.DataFile{i} = fullfile(RUNTIME.DataDir,dfn);

    if exist(RUNTIME.DataFile{i},'file')
        oldstate = recycle('on');
        delete(RUNTIME.DataFile{i});
        recycle(oldstate);
    end
    save(RUNTIME.DataFile{i},'info','-v6');

    RUNTIME.ON_HOLD(i) = false;


    % Initialize data structure
    for j = 1:length(RUNTIME.TRIALS(i).readparams_)
        RUNTIME.TRIALS(i).DATA.(RUNTIME.TRIALS(i).readparams_{j}) = [];
    end    
    RUNTIME.TRIALS(i).DATA.ResponseCode = [];
    RUNTIME.TRIALS(i).DATA.TrialID = [];
    RUNTIME.TRIALS(i).DATA.ComputerTimestamp = [];
    
end

% 
% for i = 1:RUNTIME.TDT.nModules
% 
%     for cc = bmn
%         c = sprintf('%sStr',char(cc));
%         ind = ismember(RUNTIME.TDT.devinfo(i).tags,RUNTIME.(c));
%         if ~any(ind), continue; end
%         RUNTIME.(sprintf('%sIdx',char(cc)))(ind) = i;
%     end
% 
% end


for i = 1:RUNTIME.NSubjects
    % Initialize first trial
    RUNTIME.TRIALS(i).TrialIndex = 1;
    try
        n = feval(RUNTIME.TRIALS(i).trialfunc,RUNTIME.TRIALS(i));
        if isstruct(n)
            RUNTIME.TRIALS(i).trials       = n.trials;
            RUNTIME.TRIALS(i).NextTrialID  = n.NextTrialID;
            RUNTIME.TRIALS(i).activeTrials = n.activeTrials;
            RUNTIME.TRIALS(i).UserData     = n.UserData;
        elseif isscalar(n) 
            RUNTIME.TRIALS(i).NextTrialID = n;
        else
            error('Invalid output from custom trial selection function ''%s''',RUNTIME.TRIALS(i).trialfunc)
        end
    catch me
        errordlg(sprintf('Error in Custom Trial Selection Function "%s" on line %d\n\n%s\n%s', ...
            me.stack(1).name,me.stack(1).line,me.identifier,me.message));
        rethrow(me)
    end
    RUNTIME.TRIALS(i).TrialCount(RUNTIME.TRIALS(i).NextTrialID) = 1;
    




    % 1. Send trigger to reset components before updating parameters
    % 2. Update parameter tags
    % 3. Trigger first new trial
    if RUNTIME.usingSynapse
        TrigSYNTrial(AX,RUNTIME.TRIALS(i).moduleName,RUNTIME.ResetTrigStr{1});  
        UpdateSYNtags(AX,RUNTIME.TRIALS(i));  
        TrigSYNTrial(AX,RUNTIME.TRIALS(i).moduleName,RUNTIME.NewTrialStr{1}); 

    else
        TrigRPTrial(AX(RUNTIME.ResetTrigIdx(i)),RUNTIME.ResetTrigStr{i});
        UpdateRPtags(AX,RUNTIME.TRIALS(i));
        TrigRPTrial(AX(RUNTIME.NewTrialIdx(i)),RUNTIME.NewTrialStr{i});
    end



    
end











