function TRIALS = cl_Aversive_GONOGO(TRIALS)
% TRIALS = cl_Aversive_GONOGO(TRIALS)
% 
% TRIALS is a structure which has many subfields used during an experiment.
% Below are some important subfields:
% 
% TRIALS.TrialIndex  ... Keeps track of each completed trial
% TRIALS.trials      ... A cell matrix in which each column is a different
%                        parameter and each row is a unique set of
%                        parameters (called a "trial")
% TRIALS.readparams  ... Parameter tag names for reading values from a
%                        running TDT circuit. The position of the parameter
%                        tag name in this array is the same as the position
%                        of its corresponding parameters (column) in
%                        TRRIALS.trials.
% TRIALS.writeparams ... Parameter tag names writing values from a
%                        running TDT circuit. The position of the parameter
%                        tag name in this array is the same as the position
%                        of its corresponding parameters (column) in
%                        TRIALS.trials.
% TRIALS.TrialCount  ... This field is an Nx1 integer array with N unique
%                        trials. Indices get incremented each time that
%                        trial is run.
% TRIALS.NextTrialID ... Update this field with a scalar index to indicate
%                        which trial to run next.
%
%
% See also, SelectTrial


loc = TRIALS.writeParamIdx;

activeTrials = TRIALS.activeTrials;



% Make Software parameters easier to acces
% note: these software parameters are generated by the gui which launches
% after the first trial, therefore they can only be accessed after the GUI
% has been created
sp = TRIALS.S.Module.Parameters;
sn = {sp.validName};
for j = 1:length(sp), SP.(sn{j}) = sp(j); end

if TRIALS.TrialIndex == 1
    % THIS INDICATES THAT WE ARE ABOUT TO BEGIN THE FIRST TRIAL.
    % THIS IS A GOOD PLACE TO TAKE CARE OF ANY SETUP TASKS LIKE PROMPTING
    % THE USER FOR CUSTOM PARAMETERS, ETC.


    % Aversive GO-NOGO always starts with a NOGO trial
    i = [TRIALS.trials{:,loc.TrialType}] == 0; % NOGO TrialType = 0
    TRIALS.NextTrialID = find(i);
    return
end

all.AMdepths = [TRIALS.trials{:,loc.AMdepth}];
all.TrialTypes = [TRIALS.trials{:,loc.TrialType}];


if SP.ReminderTrials.Value
    i = all.AMdepths == max(all.AMdepths) & activeTrials;
    TRIALS.NextTrialID = find(i);
    return
end

history.AMdepths = [TRIALS.DATA.AMdepth];
history.TrialTypes = [TRIALS.DATA.TrialType];

lastAMdepth = history.AMdepths(end);

valid.AMdepths = all.AMdepths(activeTrials);
valid.TrialTypes = all.TrialTypes(activeTrials);

switch SP.TrialOrder.Value
    case 'Descending'
        valid.AMdepths = sort(valid.AMdepths,'descend');
        i = find(valid.AMdepths < lastAMdepth-1e-6,1);
        if isempty(i)
            nextAMdepth = max(valid.AMdepths);
        else
            nextAMdepth = valid.AMdepths(i);
        end

    case 'Ascending'
        valid.AMdepths = sort(valid.AMdepths,'ascend');
        i = find(valid.AMdepths > lastAMdepth+1e-6,1);
        if isempty(i)
            nextAMdepth = min(valid.AMdepths);
        else
            nextAMdepth = valid.AMdepths(i);
        end

    case 'Random'
        % TO DO: ADD RULE FOR MAX CONSECUTIVE NOGO TRIALS
        maxNOGO = SP.ConsecutiveNOGO_max.Value;
        minNOGO = SP.ConsecutiveNOGO_min.Value;
        n = sum(history.TrialTypes(end-maxNOGO:end)==1);
        if n > maxNOGO % next trial must be GO (0)
            idx = find(valid.TrialTypes==0);
        elseif n < minNOGO % next trial must be NOGO (1)
            idx = find(valid.TrialTypes==1);
        else
            idx = 1:length(history.TrialTypes);
        end
        r = randi(length(idx));
        i = idx(r);
        nextAMdepth = valid.AMdepths(i);

end

TRIALS.NextTrialID = find(all.AMdepths == nextAMdepth);

