function TRIALS = cl_Aversive_GONOGO(TRIALS)
% TRIALS = cl_Aversive_GONOGO(TRIALS)
% 
% TRIALS is a structure which has many subfields used during an experiment.
% Below are some important subfields:
% 
% TRIALS.TrialIndex  ... Keeps track of each completed trial
% TRIALS.trials      ... A cell matrix in which each column is a different
%                        parameter and each row is a unique set of
%                        parameters (called a "trial")
% TRIALS.readparams  ... Parameter tag names for reading values from a
%                        running TDT circuit. The position of the parameter
%                        tag name in this array is the same as the position
%                        of its corresponding parameters (column) in
%                        TRRIALS.trials.
% TRIALS.writeparams ... Parameter tag names writing values from a
%                        running TDT circuit. The position of the parameter
%                        tag name in this array is the same as the position
%                        of its corresponding parameters (column) in
%                        TRIALS.trials.
% TRIALS.TrialCount  ... This field is an Nx1 integer array with N unique
%                        trials. Indices get incremented each time that
%                        trial is run.
% TRIALS.NextTrialID ... Update this field with a scalar index to indicate
%                        which trial to run next.
%
%
% See also, SelectTrial

persistent nNOGOs

TT.NOGO = 1;
TT.GO = 0;

loc = TRIALS.writeParamIdx;
reminderInd = [TRIALS.trials{:,loc.Reminder}];

all.AMdepths = [TRIALS.trials{:,loc.AMdepth}];
all.TrialTypes = [TRIALS.trials{:,loc.TrialType}];

% Make Software parameters easier to acces
% note: these software parameters are generated by the gui which launches
% after the first trial, therefore they can only be accessed after the GUI
% has been created
sp = TRIALS.S.Module.Parameters;
sn = {sp.validName};
for j = 1:length(sp), SP.(sn{j}) = sp(j); end

if TRIALS.TrialIndex == 1
    % THIS INDICATES THAT WE ARE ABOUT TO BEGIN THE FIRST TRIAL.
    % THIS IS A GOOD PLACE TO TAKE CARE OF ANY SETUP TASKS LIKE PROMPTING
    % THE USER FOR CUSTOM PARAMETERS, ETC.


    % Aversive GO-NOGO always starts with a GO REMINDER trial
    TRIALS.NextTrialID = find(reminderInd,1);
    return
end

% REMINDER Trials
if SP.ReminderTrials.Value
    TRIALS.NextTrialID = find(reminderInd,1);
    return
end

history.AMdepths = [TRIALS.DATA.AMdepth];
history.TrialTypes = [TRIALS.DATA.TrialType];

lastAMdepth = history.AMdepths(history.TrialTypes==TT.GO);
lastAMdepth = lastAMdepth(end);


% Determine if enough consecutive NOGO trials have been presented
NOGOmax = SP.ConsecutiveNOGO_max.Value;
NOGOmin = SP.ConsecutiveNOGO_min.Value;

if isempty(nNOGOs)
    nNOGOs = randi([NOGOmin, NOGOmax]);
end

nBack = min(nNOGOs,TRIALS.TrialIndex-1);

% how many NOGOs have we had in the last n trials?
nRecentNOGOs = sum(history.TrialTypes(end-nBack+1:end)==TT.NOGO);
if nRecentNOGOs < nNOGOs % next trial must be a NOGO
    TRIALS.NextTrialID = find(all.TrialTypes == TT.NOGO,1);
    return
end



% set nNOGOs for next block
nNOGOs = randi([NOGOmin, NOGOmax]);

activeTrials = TRIALS.activeTrials;

valid.AMdepths = all.AMdepths(activeTrials & all.TrialTypes == TT.GO & ~reminderInd);
valid.TrialTypes = all.TrialTypes(activactiveTrials & all.TrialTypes == TT.GO & ~reminderIndeTrials);

% time for a GO trial
switch SP.TrialOrder.Value
    case 'Descending'
        valid.AMdepths = sort(valid.AMdepths,'descend');
        i = find(valid.AMdepths < lastAMdepth-1e-6,1);
        if isempty(i)
            nextAMdepth = max(valid.AMdepths);
        else
            nextAMdepth = valid.AMdepths(i);
        end

    case 'Ascending'
        valid.AMdepths = sort(valid.AMdepths,'ascend');
        i = find(valid.AMdepths > lastAMdepth+1e-6,1);
        if isempty(i)
            nextAMdepth = min(valid.AMdepths);
        else
            nextAMdepth = valid.AMdepths(i);
        end

    case 'Random'
        % TO DO: ADD RULE FOR MAX CONSECUTIVE NOGO TRIALS
        % n = sum(history.TrialTypes(end-NOGOmax:end)==TT.GO);
        % if n > NOGOmax % next trial must be GO (1)
        %     idx = find(valid.TrialTypes==TT.GO);
        % elseif n < NOGOmin % next trial must be NOGO (0)
        %     idx = find(valid.TrialTypes==TT.GO);
        % else
        %     idx = 1:length(history.TrialTypes);
        % end
        % r = randi(length(idx));
        % i = idx(r);
        % nextAMdepth = valid.AMdepths(i);

end

TRIALS.NextTrialID = find(all.AMdepths == nextAMdepth & ~reminderInd);

