function TRIALS = cl_TrialSelection_Appetitive_GONOGO(TRIALS)
% TRIALS = cl_TrialSelection_Appetitive_GONOGO(TRIALS)
% 
% TRIALS is a structure which has many subfields used during an experiment.
% Below are some important subfields:
% 
% TRIALS.TrialIndex  ... Keeps track of each completed trial
% TRIALS.trials      ... A cell matrix in which each column is a different
%                        parameter and each row is a unique set of
%                        parameters (called a "trial")
% TRIALS.readparams  ... Parameter tag names for reading values from a
%                        running TDT circuit. The position of the parameter
%                        tag name in this array is the same as the position
%                        of its corresponding parameters (column) in
%                        TRRIALS.trials.
% TRIALS.writeparams ... Parameter tag names writing values from a
%                        running TDT circuit. The position of the parameter
%                        tag name in this array is the same as the position
%                        of its corresponding parameters (column) in
%                        TRIALS.trials.
% TRIALS.TrialCount  ... This field is an Nx1 integer array with N unique
%                        trials. Indices get incremented each time that
%                        trial is run.
% TRIALS.NextTrialID ... Update this field with a scalar index to indicate
%                        which trial to run next.
%
%
% See also, SelectTrial

persistent nNOGOs

reminderTrial = TRIALS.HW.find_parameter('~ReminderTrial',includeInvisible=true);
deliverTrials = TRIALS.HW.find_parameter('~TrialDelivery',includeInvisible=true);


TT.GO   = 0;
TT.NOGO = 1;
TT.REMIND = 2;

for fn = string(fieldnames(TRIALS.writeParamIdx))'
    all.(fn) = [TRIALS.trials{:,TRIALS.writeParamIdx.(fn)}];
end

TRIALS.NextTrialID = find(all.TrialType == TT.NOGO,1); % default

% Make Software parameters easier to acces
% note: these software parameters are generated by the gui which launches
% after the first trial, therefore they can only be accessed after the GUI
% has been created
sp = TRIALS.S.Module.Parameters;
if isempty(sp), return; end % gui not yet loaded
sn = {sp.validName};
for j = 1:length(sp), SP.(sn{j}) = sp(j); end



if SP.ReminderTrials.Value == 1
    vprintf(4,'Setting up for a Reminder trial')
    TRIALS.NextTrialID = find(all.TrialType == TT.REMIND,1);
    reminderTrial.Value = true;
    return
end

reminderTrial.Value = false;


% % make first trial NO GO
% if TRIALS.TrialIndex == 1 || deliverTrials.Value == 0
%     TRIALS.NextTrialID = find(all.TrialType == TT.NOGO,1);
%     return
% end



RC = epsych.BitMask.decodeResponseCodes([TRIALS.DATA.RespCode]);


% Determine if enough consecutive NOGO trials have been presented
NOGOmax = SP.ConsecutiveNOGO_max.Value;
NOGOmin = SP.ConsecutiveNOGO_min.Value;



if isempty(nNOGOs) || nNOGOs > NOGOmax % can happen if user changes max value after nNOGOs was set
    nNOGOs = randi([NOGOmin, NOGOmax]);
end

nBack = min(nNOGOs,TRIALS.TrialIndex-1);

% how many NOGOs have we had in the last n trials?
nRecentNOGOs = sum(RC.("TrialType_"+TT.NOGO)(end-nBack+1:end));
if nRecentNOGOs < nNOGOs % next trial must be a NOGO
    TRIALS.NextTrialID = find(all.TrialType == TT.NOGO,1);
    return
end

% % if the gerbil got a correct reject, then give an easy one
% if RC.CorrectReject(end)
%     TRIALS.NextTrialID = find(all.TrialType == TT.REMIND,1);
%     return
% end


% set nNOGOs for next block
nNOGOs = randi([NOGOmin, NOGOmax]);




% REMINDER Trials
if SP.ReminderTrials.Value
    TRIALS.NextTrialID = find(all.TrialType == TT.REMIND,1);
    return
end

activeTrials = false(size(all.TrialType));
activeTrials(all.TrialType~=TT.REMIND) = TRIALS.activeTrials;


valid.Depth = all.Depth(activeTrials & all.TrialType == TT.GO);
valid.TrialType = all.TrialType(activeTrials & all.TrialType == TT.GO);

goTrials = RC.("TrialType_"+TT.GO);
lastGoTrialIdx = find(goTrials,1,'last');
lastStim = [];
stim = [TRIALS.DATA.Depth];
if ~isempty(lastGoTrialIdx), lastStim = stim(lastGoTrialIdx); end




% time for a GO trial
switch SP.TrialOrder.Value
    case 'Descending'
        valid.Depth = sort(valid.Depth,'descend');
        if isempty(lastStim),lastStim = inf; end
        lastStim = double(lastStim)-1e-4;
        i = find(valid.Depth < lastStim,1);
        if isempty(i)
            nextDepth = max(valid.Depth);
        else
            nextDepth = valid.Depth(i);
        end

    case 'Ascending'
        valid.Depth = sort(valid.Depth,'ascend');
        if isempty(lastStim),lastStim = -inf; end
        lastStim = double(lastStim)+1e-4;
        i = find(valid.Depth > lastStim,1);
        if isempty(i)
            nextDepth = min(valid.Depth);
        else
            nextDepth = valid.Depth(i);
        end

    case 'Random'
        % limit how far back we look
        n = length(valid.Depth);

        goTrials = stim(RC.("TrialType_"+TT.GO));
        if length(goTrials) > n
            goTrials = goTrials(end-n+1:end);
        end

        % how many times has each value been present on the last nGO trials?
        nPresentations = arrayfun(@(a) sum(isapprox(goTrials,a,"loose")),valid.Depth);

        % priorities stimuli that have been presented least
        m = min(nPresentations);
        idx = find(nPresentations == m);
        r = randi(length(idx));
        i = idx(r);
        nextDepth = valid.Depth(i);

    case 'Staircase'
        vprintf(0,1,'STAIRCASE NOT YET IMPLEMENTED')
end


% next trial id
ntid = find(all.Depth == nextDepth & all.TrialType ~= TT.REMIND);



TRIALS.NextTrialID = ntid;

